export const sampleUsers = [
  {
    name: "Alice Johnson",
    username: "alicej",
    password: "AlicePass123",
    phonenumber: "+919811223344",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=alicej1",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=alicej1cover",
    emailId: "alice.johnson@example.com",
  },
  {
    name: "Bob Smith",
    username: "bobsmith",
    password: "BobSecure123",
    phonenumber: "+919822334455",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=bobsmith",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=bobsmithcover",
    emailId: "bob.smith@example.com",
  },
  {
    name: "Charlie Brown",
    username: "charlieb",
    password: "CharBrown99",
    phonenumber: "+919833445566",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=charlieb",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=charliebcover",
    emailId: "charlie.brown@example.com",
  },
  {
    name: "Diana Prince",
    username: "dianap",
    password: "WonderDiana123",
    phonenumber: "+919844556677",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=dianap",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=dianapcover",
    emailId: "diana.prince@example.com",
  },
  {
    name: "Ethan Hunt",
    username: "ethanhunt",
    password: "Mission123E",
    phonenumber: "+919855667788",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=ethanhunt",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=ethanhuntcover",
    emailId: "ethan.hunt@example.com",
  },
  {
    name: "Fiona Gallagher",
    username: "fionag",
    password: "Fiona2023G",
    phonenumber: "+919866778899",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=fionag",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=fionagcover",
    emailId: "fiona.g@example.com",
  },
  {
    name: "George Martin",
    username: "georgem",
    password: "GeoPass123",
    phonenumber: "+919877889900",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=georgem",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=georgemcover",
    emailId: "george.m@example.com",
  },
  {
    name: "Hannah Wells",
    username: "hannahw",
    password: "HannahW2024",
    phonenumber: "+919888900011",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=hannahw",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=hannahwcover",
    emailId: "hannah.wells@example.com",
  },
  {
    name: "Ian Curtis",
    username: "iancurtis",
    password: "CurtisJoy123",
    phonenumber: "+919899011122",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=iancurtis",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=iancurtiscover",
    emailId: "ian.curtis@example.com",
  },
  {
    name: "Jenna Ortega",
    username: "jennaortega",
    password: "Ortega123J",
    phonenumber: "+919900122233",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=jennaortega",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=jennaortegacover",
    emailId: "jenna.ortega@example.com",
  },
  {
    name: "Kevin Tran",
    username: "kevintran",
    password: "KevinTran99",
    phonenumber: "+919911233344",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=kevintran",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=kevintrancover",
    emailId: "kevin.tran@example.com",
  },
  {
    name: "Lara Croft",
    username: "laracroft",
    password: "LaraCroft123",
    phonenumber: "+919922344455",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=laracroft",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=laracroftcover",
    emailId: "lara.croft@example.com",
  },
  {
    name: "Mike Ross",
    username: "mikeross",
    password: "SuitsMike99",
    phonenumber: "+919933455566",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=mikeross",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=mikerosscover",
    emailId: "mike.ross@example.com",
  },
  {
    name: "Nina Dobrev",
    username: "ninad",
    password: "NinaD2024",
    phonenumber: "+919944566677",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=ninad",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=ninadcover",
    emailId: "nina.dobrev@example.com",
  },
  {
    name: "Oscar Isaac",
    username: "oscarisaac",
    password: "Isaac2023O",
    phonenumber: "+919955677788",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=oscarisaac",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=oscarisaaccover",
    emailId: "oscar.isaac@example.com",
  },
  {
    name: "Priya Sharma",
    username: "priyash",
    password: "Priya123S",
    phonenumber: "+919966788899",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=priyash",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=priyashcover",
    emailId: "priya.sharma@example.com",
  },
  {
    name: "Quentin Blake",
    username: "quentinb",
    password: "QBlake2023",
    phonenumber: "+919977899900",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=quentinb",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=quentinbcover",
    emailId: "quentin.blake@example.com",
  },
  {
    name: "Ritika Gupta",
    username: "ritikag",
    password: "RitikaG2024",
    phonenumber: "+919988900011",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=ritikag",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=ritikagcover",
    emailId: "ritika.gupta@example.com",
  },
  {
    name: "Steve Rogers",
    username: "captainsteve",
    password: "CapShield1",
    phonenumber: "+919999011122",
    avatar:
      "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=captainsteve",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=captainstevecover",
    emailId: "steve.rogers@example.com",
  },
  {
    name: "Tara Singh",
    username: "taras",
    password: "TaraSingh123",
    phonenumber: "+919900122231",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=taras",
    coverImage: "https://api.dicebear.com/9.x/glass/svg?seed=tarascover",
    emailId: "tara.singh@example.com",
  },
];
